### ISSUE TITLE
Transform not found?

### ISSUE THREAD

**Issue by liaoqifeng** [cryptocoinjs/keccak#21]
Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null

const { Transform } = require('stream')

Why?

**Comment by fanatid** [comment]
What is your environment? browser / node / node version / tools

**Comment by maximgeerinck** [comment]
Ran into a similar issue, was using a backend library (eth-sig-util) on the frontend. Using ethersJS alternative fixed it for me.

**Comment by fanatid** [comment]
If you use `webpack` as a bundler, do you have `resolve.fallback` to the `stream` module? https://webpack.js.org/configuration/resolve/#resolvefallback

**Comment by byterose** [comment]
I am using SvelteKit (Vite) and have the same problem.

**Comment by byterose** [comment]
@liaoqifeng This error occurs because stream is unstable due to your node version. Therefore I recommend to use the [readable-stream](https://www.npmjs.com/package/readable-stream) instead of [stream](https://www.npmjs.com/package/stream).

In #22 you can see what changes need to be applied in order to solve this issue.

If the maintainer of this repo does not decide to replace __stream__ with __readable-stream__ you can use [patch-package](https://www.npmjs.com/package/patch-package) to edit the node module yourself.

**Comment by byterose** [comment]
@liaoqifeng This error occurs because __stream__ is unstable due to your node version. Therefore I recommend to use the [readable-stream](https://www.npmjs.com/package/readable-stream) module instead of [stream](https://www.npmjs.com/package/stream).

In #22 you can see what changes need to be applied in order to solve this issue.

If the maintainer of this repo does not decide to replace __stream__ with __readable-stream__ you can use [patch-package](https://www.npmjs.com/package/patch-package) to edit the node module yourself.
